// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABw8w0khBwZxBjYd1_XVhHBELkJBXeLqM',
    appId: '1:394872047782:web:fcc2e05e3e18dcd44e4c67',
    messagingSenderId: '394872047782',
    projectId: 'sinflixberkay',
    authDomain: 'sinflixberkay.firebaseapp.com',
    storageBucket: 'sinflixberkay.firebasestorage.app',
    measurementId: 'G-WVPLWDDW0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJeyRzb91uxR302HTWl6z_aOT2KbZ-JIw',
    appId: '1:394872047782:android:6d3cade0dd4244bc4e4c67',
    messagingSenderId: '394872047782',
    projectId: 'sinflixberkay',
    storageBucket: 'sinflixberkay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6Elod_JXtjCVRjN7UOHeuWVOd_-m-d0',
    appId: '1:394872047782:ios:d3c898429dd02ca14e4c67',
    messagingSenderId: '394872047782',
    projectId: 'sinflixberkay',
    storageBucket: 'sinflixberkay.firebasestorage.app',
    iosBundleId: 'com.example.sinflix',
  );
}
